### ISSUE TITLE
升级到 3.0.9 和 3.0.10 报错

### ISSUE THREAD

**Issue by chanjsq** [overtrue/laravel-lang#36]
Lumen 5.6 + ValidationException，升级到 3.0.9 和 3.0.10 报错，降级到 3.0.8 正常。

```
[2018-09-02 16:06:18] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Illuminate\Translation\Translator::__construct() must implement interface Illuminate\Contracts\Translation\Loader, null given, called in /Users/huachen/Projects/dongri/api/vendor/illuminate/translation/TranslationServiceProvider.php on line 33 in /Users/huachen/Projects/dongri/api/vendor/illuminate/translation/Translator.php:60
Stack trace:
#0 /Users/huachen/Projects/dongri/api/vendor/illuminate/translation/TranslationServiceProvider.php(33): Illuminate\Translation\Translator->__construct(NULL, 'zh-CN')
#1 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(764): Illuminate\Translation\TranslationServiceProvider->Illuminate\Translation\{closure}(Object(Laravel\Lumen\Application), Array)
#2 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(646): Illuminate\Container\Container->build(Object(Closure))
#3 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(601): Illuminate\Container\Container->resolve('translator', Array)
#4 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(223): Illuminate\Container\Container->make('translator', Array)
#5 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(1210): Laravel\Lumen\Application->make('translator')
#6 /Users/huachen/Projects/dongri/api/vendor/illuminate/validation/ValidationServiceProvider.php(36): Illuminate\Container\Container->offsetGet('translator')
#7 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(764): Illuminate\Validation\ValidationServiceProvider->Illuminate\Validation\{closure}(Object(Laravel\Lumen\Application), Array)
#8 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(646): Illuminate\Container\Container->build(Object(Closure))
#9 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(601): Illuminate\Container\Container->resolve('validator', Array)
#10 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(223): Illuminate\Container\Container->make('validator', Array)
#11 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(524): Laravel\Lumen\Application->make('validator')
#12 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(764): Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Laravel\Lumen\Application), Array)
#13 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(646): Illuminate\Container\Container->build(Object(Closure))
#14 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(601): Illuminate\Container\Container->resolve('validator', Array)
#15 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(223): Illuminate\Container\Container->make('validator', Array)
#16 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/helpers.php(38): Laravel\Lumen\Application->make('validator')
#17 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/ProvidesConvenienceMethods.php(206): app('validator')
#18 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/ProvidesConvenienceMethods.php(64): Laravel\Lumen\Routing\Controller->getValidationFactory()
#19 /Users/huachen/Projects/dongri/api/app/Http/Controllers/V2/SolutionRecordsController.php(15): Laravel\Lumen\Routing\Controller->validate(Object(Illuminate\Http\Request), Array)
#20 [internal function]: App\Http\Controllers\V2\SolutionRecordsController->index(Object(Illuminate\Http\Request))
#21 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#24 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#25 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(373): Illuminate\Container\Container->call(Array, Array)
#26 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(339): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#27 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(313): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\V2\SolutionRecordsController), 'index', Array)
#28 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(275): Laravel\Lumen\Application->callControllerAction(Array)
#29 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(260): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#30 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#32 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /Users/huachen/Projects/dongri/api/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(35): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /Users/huachen/Projects/dongri/api/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /Users/huachen/Projects/dongri/api/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /Users/huachen/Projects/dongri/api/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /Users/huachen/Projects/dongri/api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#44 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#45 /Users/huachen/Projects/dongri/api/public/index.php(28): Laravel\Lumen\Application->run()
#46 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Illuminate\\Translation\\Translator::__construct() must implement interface Illuminate\\Contracts\\Translation\\Loader, null given, called in /Users/huachen/Projects/dongri/api/vendor/illuminate/translation/TranslationServiceProvider.php on line 33 at /Users/huachen/Projects/dongri/api/vendor/illuminate/translation/Translator.php:60)
[stacktrace]
#0 /Users/huachen/Projects/dongri/api/vendor/illuminate/translation/TranslationServiceProvider.php(33): Illuminate\\Translation\\Translator->__construct(NULL, 'zh-CN')
#1 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(764): Illuminate\\Translation\\TranslationServiceProvider->Illuminate\\Translation\\{closure}(Object(Laravel\\Lumen\\Application), Array)
#2 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(646): Illuminate\\Container\\Container->build(Object(Closure))
#3 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(601): Illuminate\\Container\\Container->resolve('translator', Array)
#4 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(223): Illuminate\\Container\\Container->make('translator', Array)
#5 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(1210): Laravel\\Lumen\\Application->make('translator')
#6 /Users/huachen/Projects/dongri/api/vendor/illuminate/validation/ValidationServiceProvider.php(36): Illuminate\\Container\\Container->offsetGet('translator')
#7 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(764): Illuminate\\Validation\\ValidationServiceProvider->Illuminate\\Validation\\{closure}(Object(Laravel\\Lumen\\Application), Array)
#8 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(646): Illuminate\\Container\\Container->build(Object(Closure))
#9 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(601): Illuminate\\Container\\Container->resolve('validator', Array)
#10 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(223): Illuminate\\Container\\Container->make('validator', Array)
#11 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(524): Laravel\\Lumen\\Application->make('validator')
#12 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(764): Laravel\\Lumen\\Application->Laravel\\Lumen\\{closure}(Object(Laravel\\Lumen\\Application), Array)
#13 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(646): Illuminate\\Container\\Container->build(Object(Closure))
#14 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(601): Illuminate\\Container\\Container->resolve('validator', Array)
#15 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Application.php(223): Illuminate\\Container\\Container->make('validator', Array)
#16 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/helpers.php(38): Laravel\\Lumen\\Application->make('validator')
#17 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/ProvidesConvenienceMethods.php(206): app('validator')
#18 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/ProvidesConvenienceMethods.php(64): Laravel\\Lumen\\Routing\\Controller->getValidationFactory()
#19 /Users/huachen/Projects/dongri/api/app/Http/Controllers/V2/SolutionRecordsController.php(15): Laravel\\Lumen\\Routing\\Controller->validate(Object(Illuminate\\Http\\Request), Array)
#20 [internal function]: App\\Http\\Controllers\\V2\\SolutionRecordsController->index(Object(Illuminate\\Http\\Request))
#21 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#24 /Users/huachen/Projects/dongri/api/vendor/illuminate/container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#25 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(373): Illuminate\\Container\\Container->call(Array, Array)
#26 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(339): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#27 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(313): Laravel\\Lumen\\Application->callLumenController(Object(App\\Http\\Controllers\\V2\\SolutionRecordsController), 'index', Array)
#28 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(275): Laravel\\Lumen\\Application->callControllerAction(Array)
#29 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(260): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#30 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(160): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))
#33 /Users/huachen/Projects/dongri/api/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(35): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/huachen/Projects/dongri/api/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))
#37 /Users/huachen/Projects/dongri/api/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/huachen/Projects/dongri/api/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))
#41 /Users/huachen/Projects/dongri/api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#44 /Users/huachen/Projects/dongri/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\\Lumen\\Application->dispatch(NULL)
#45 /Users/huachen/Projects/dongri/api/public/index.php(28): Laravel\\Lumen\\Application->run()
#46 {main}
"} 
```

**Comment by linganmin** [comment]
刚看到超哥最新的代码已经修复了这个问题是因为这句
```
return (new FileLoader($app['files'], $app['path.lang'], $paths))
                ->addJsonPath($jsonPath);
```

**Comment by linganmin** [comment]
刚看到超哥最新的代码已经修复了这个问题是因为这句
```
return (new FileLoader($app['files'], $app['path.lang'], $paths))
                ->addJsonPath($jsonPath);
```

**Comment by chanjsq** [comment]
@linganmin 谢谢
